# Generated by Django 6.0.4 on 2026-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('test_type', models.CharField(choices=[('ielts', 'IELTS Mock'), ('cefr', 'CEFR Test')], max_length=10)),
                ('note', models.TextField(blank=True, help_text="Qo'shimcha izoh")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('viewed', "Ko'rilgan"), ('called', "Qo'ng'iroq qilindi"), ('done', 'Bajarildi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
