# Generated by Django 6.0.4 on 2026-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PolyglotLC', max_length=200)),
                ('site_description', models.TextField(blank=True, default="Professional o'quv markazi")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('phone_1', models.CharField(default='+998 90 123 45 67', max_length=20)),
                ('phone_2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(default='info@polyglotlc.uz', max_length=254)),
                ('address', models.TextField(blank=True, default='Toshkent shahri')),
                ('telegram', models.URLField(blank=True, default='https://t.me/polyglotlc')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/polyglotlc')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@polyglotlc')),
                ('facebook', models.URLField(blank=True, default='')),
                ('tiktok', models.URLField(blank=True, default='')),
                ('weekday_hours', models.CharField(default='09:00 - 21:00', max_length=50)),
                ('weekend_hours', models.CharField(default='10:00 - 18:00', max_length=50)),
                ('weekday_label', models.CharField(default='Dushanba - Shanba', max_length=50)),
                ('weekend_label', models.CharField(default='Yakshanba', max_length=50)),
                ('hero_title', models.CharField(blank=True, default='Kelajagingizni biz bilan boshlang!', max_length=300)),
                ('hero_subtitle', models.TextField(blank=True, default="Ingliz tili, IT, matematika va boshqa yo'nalishlar bo'yicha professional ta'lim")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('stats_students', models.CharField(default='300+', max_length=20)),
                ('stats_experience', models.CharField(default='5+', max_length=20)),
                ('stats_teachers', models.CharField(default='30+', max_length=20)),
                ('stats_branches', models.CharField(default='2', max_length=20)),
                ('meta_title', models.CharField(blank=True, default="PolyglotLC - Professional o'quv markazi", max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
