# Generated by Django 6.0.4 on 2026-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('working_hours', models.CharField(default='Dush-Shan: 09:00-20:00', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
