# Generated by Django 6.0.4 on 2026-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('news', 'Markaz yangiliklari'), ('english', 'Ingliz tili'), ('it', 'IT'), ('math', 'Matematika'), ('other', 'Boshqa')], max_length=20),
        ),
    ]
