# Generated by Django 6.0.4 on 2026-04-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('certificate_name', models.CharField(max_length=200)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('language', 'Til kurslari'), ('it', 'IT / Dasturlash'), ('other', 'Boshqa')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text="Oylik narx (so'm)")),
                ('status', models.CharField(choices=[('published', 'Nashr qilingan'), ('draft', 'Draft')], default='published', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('language', 'Til kurslari'), ('it', 'IT / Dasturlash'), ('other', 'Boshqa')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certificates', models.TextField(blank=True, help_text='Sertifikatlar (vergul bilan)')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('viewed', "Ko'rilgan"), ('accepted', 'Qabul qilindi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
