# Generated by Django 6.0.4 on 2026-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(choices=[('english', 'English'), ('ielts', 'IELTS'), ('cefr', 'CEFR'), ('sat', 'SAT'), ('math', 'Matematika'), ('history', 'Tarix'), ('russian', 'Rus tili'), ('it', 'IT / Dasturlash'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='direction',
            field=models.CharField(choices=[('english', 'English'), ('ielts', 'IELTS'), ('cefr', 'CEFR'), ('sat', 'SAT'), ('math', 'Matematika'), ('history', 'Tarix'), ('russian', 'Rus tili'), ('it', 'IT / Dasturlash'), ('other', 'Boshqa')], max_length=20),
        ),
    ]
