# Generated by Django 6.0.4 on 2026-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_direction_alter_teacher_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(choices=[('english', 'Ingliz tili'), ('math', 'Matematika'), ('history', 'Tarix'), ('it', 'IT / Dasturlash'), ('russian', 'Rus tili'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='direction',
            field=models.CharField(choices=[('english', 'Ingliz tili'), ('math', 'Matematika'), ('history', 'Tarix'), ('it', 'IT / Dasturlash'), ('russian', 'Rus tili'), ('other', 'Boshqa')], max_length=20),
        ),
    ]
