# Generated by Django 6.0.4 on 2026-04-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, default='', help_text="Batafsil ma'lumot (inner sahifa uchun)"),
        ),
        migrations.CreateModel(
            name='TeacherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teachers/certificates/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_images', to='courses.teacher')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
